export const networks = ["Goerli", "Sepolia", "Stylus"]

export const faucetInfo = {
  Goerli: [
    {
      name: "QuickNode",
      link: "https://faucet.quicknode.com/arbitrum/goerli",
      maxAmount: "0.05",
      minAmount: "0.025",
      recover: "12 Hours",
      dailySupply: "None",
      required: "Mainnet Balance",
      image: "faucets/quicknode.svg",
      address: "0xA88f1CD3379FC5F407BcEF0c0b396D2314A6Ad61",
    },
  ],
  Sepolia: [
    {
      name: "QuickNode",
      link: "https://faucet.quicknode.com/arbitrum/sepolia",
      maxAmount: "0.1",
      minAmount: "0.05",
      recover: "12 Hours",
      dailySupply: "None",
      required: "Mainnet Balance",
      image: "faucets/quicknode.svg",
      address: "0x31957B0C184a0870416D2518084adA6E24759193",
    },
    {
      name: "Alchemy",
      link: "https://www.alchemy.com/faucets/arbitrum-sepolia",
      maxAmount: "0.5",
      minAmount: "0.5",
      recover: "12 Hours",
      dailySupply: "None",
      required: "Mainnet Balance",
      image: "faucets/alchemy.png",
      address: "0xD8Ea779b8FFC1096CA422D40588C4c0641709890",
    },
    {
      name: "Triangle Platform",
      link: "https://faucet.triangleplatform.com/arbitrum/sepolia",
      maxAmount: "0.001",
      minAmount: "0.001",
      recover: "24 Hours",
      dailySupply: "None",
      required: "Captcha",
      image: "faucets/trianglefaucet.png",
      address: "0x007aB5199B6c57F7aA51bc3D0604a43505501a0C",
    },
    {
      name: "LearnWeb3",
      link: "https://learnweb3.io/faucets/arbitrum_sepolia/",
      maxAmount: "0.01",
      minAmount: "0.01",
      recover: "24 Hours",
      dailySupply: "None",
      required: "Captcha",
      image: "faucets/learnweb3.png",
      address: "0x625BCC1142E97796173104A6e817Ee46C593b3C5",
    },
    {
      name: "BWare Labs",
      link: "https://bwarelabs.com/faucets/arbitrum-sepolia",
      maxAmount: "0.05",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/bwarelabs.svg",
    },
    {
      name: "Blast API",
      link: "https://blastapi.io/faucets/arbitrum-sepolia",
      maxAmount: "0.075",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/blast.png",
    },
    {
      name: "Chainlink ",
      link: "https://faucets.chain.link/arbitrum-sepolia",
      maxAmount: "0.25",
      minAmount: "0.25",
      recover: "24 Hours",
      dailySupply: "None",
      required: "Github",
      image: "faucets/chainlink.png",
    },
  ],
  Stylus: [
    {
      name: "BWare Labs",
      link: "https://bwarelabs.com/faucets/arbitrum-stylus-testnet",
      maxAmount: "0.05",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/bwarelabs.svg",
      address: "0xb76debe515171c0fe30b98f117bb9c11bbb6ad5d",
    },
    {
      name: "Blast API",
      link: "https://blastapi.io/faucets/arbitrum-stylus",
      maxAmount: "0.075",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/blast.png",
    },
  ],
}
