export const networks = ["Goerli", "Sepolia", "Stylus"]

export const faucetInfo = {
  Goerli: [
    {
      name: "Triangle Platform",
      link: "https://faucet.triangleplatform.com/arbitrum/goerli",
      maxAmount: "0.001",
      minAmount: "0.001",
      recover: "24 Hours",
      dailySupply: "None",
      required: "Captcha",
      image: "faucets/trianglefaucet.png",
      address: "0x007aB5199B6c57F7aA51bc3D0604a43505501a0C",
    },
    {
      name: "BWare Labs",
      link: "https://bwarelabs.com/faucets/arbitrum-testnet",
      maxAmount: "0.075",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/bwarelabs.svg",
    },
    {
      name: "QuickNode",
      link: "https://faucet.quicknode.com/arbitrum/goerli",
      maxAmount: "0.05",
      minAmount: "0.025",
      recover: "12 Hours",
      dailySupply: "None",
      required: "Mainnet Balance",
      image: "faucets/quicknode.svg",
      address: "0xA88f1CD3379FC5F407BcEF0c0b396D2314A6Ad61",
    },
  ],
  Sepolia: [
    {
      name: "QuickNode",
      link: "https://faucet.quicknode.com/arbitrum/goerli",
      maxAmount: "0.1",
      minAmount: "0.05",
      recover: "12 Hours",
      dailySupply: "None",
      required: "Mainnet Balance",
      image: "faucets/quicknode.svg",
      address: "0x31957B0C184a0870416D2518084adA6E24759193",
    },
    {
      name: "BWare Labs",
      link: "https://bwarelabs.com/faucets/arbitrum-sepolia-testnet",
      maxAmount: "0.05",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/bwarelabs.svg",
    },
  ],
  Stylus: [
    {
      name: "BWare Labs",
      link: "https://bwarelabs.com/faucets/arbitrum-stylus-testnet",
      maxAmount: "0.05",
      minAmount: "0.025",
      recover: "24 Hours",
      dailySupply: "15",
      required: "None",
      image: "faucets/bwarelabs.svg",
      address: "0xb76debe515171c0fe30b98f117bb9c11bbb6ad5d",
    },
  ],
}
